"""Database models and operations"""

from datetime import datetime
from typing import List, Optional
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session

from src.utils.config import config
from src.utils.logger import get_logger

logger = get_logger(__name__)

Base = declarative_base()


class Trade(Base):
    """Trade execution record"""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    order_id = Column(String, unique=True, index=True)
    symbol = Column(String, index=True)
    side = Column(String)  # buy/sell
    quantity = Column(Float)
    price = Column(Float)
    order_type = Column(String)  # market/limit
    status = Column(String)
    strategy = Column(String)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    profit_loss = Column(Float, nullable=True)


class Signal(Base):
    """Trading signals generated by strategies"""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String, index=True)
    signal_type = Column(String)  # buy/sell/hold
    strength = Column(Float)  # 0-1 confidence
    strategy = Column(String)
    price = Column(Float)
    reason = Column(Text)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    executed = Column(Boolean, default=False)


class SentimentData(Base):
    """Sentiment analysis results"""
    __tablename__ = "sentiment"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String, index=True)
    source = Column(String)  # reddit/twitter/news
    sentiment_score = Column(Float)  # -1 to 1
    volume = Column(Integer)  # number of mentions
    text_sample = Column(Text, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)


class PerformanceMetrics(Base):
    """Daily performance metrics"""
    __tablename__ = "performance"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(DateTime, index=True)
    portfolio_value = Column(Float)
    cash = Column(Float)
    equity = Column(Float)
    total_pl = Column(Float)
    daily_pl = Column(Float)
    daily_return = Column(Float)
    num_positions = Column(Integer)
    num_trades = Column(Integer)


class MLPrediction(Base):
    """ML model predictions"""
    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String, index=True)
    model_name = Column(String)
    prediction_type = Column(String)  # price/direction/volatility
    predicted_value = Column(Float)
    confidence = Column(Float)
    actual_value = Column(Float, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    prediction_date = Column(DateTime)  # when prediction is for


class DatabaseManager:
    """Database operations manager"""

    def __init__(self, database_url: Optional[str] = None):
        if database_url is None:
            database_url = config.trading.database_url

        self.engine = create_engine(database_url)
        Base.metadata.create_all(self.engine)
        self.SessionLocal = sessionmaker(bind=self.engine)
        logger.info(f"Database initialized at {database_url}")

    def get_session(self) -> Session:
        """Get a database session"""
        return self.SessionLocal()

    def save_trade(self, trade_data: dict) -> Trade:
        """Save a trade record"""
        session = self.get_session()
        try:
            trade = Trade(**trade_data)
            session.add(trade)
            session.commit()
            session.refresh(trade)
            logger.info(f"Trade saved: {trade.symbol} {trade.side} {trade.quantity}")
            return trade
        except Exception as e:
            session.rollback()
            logger.error(f"Error saving trade: {e}")
            raise
        finally:
            session.close()

    def save_signal(self, signal_data: dict) -> Signal:
        """Save a trading signal"""
        session = self.get_session()
        try:
            signal = Signal(**signal_data)
            session.add(signal)
            session.commit()
            session.refresh(signal)
            return signal
        except Exception as e:
            session.rollback()
            logger.error(f"Error saving signal: {e}")
            raise
        finally:
            session.close()

    def save_sentiment(self, sentiment_data: dict) -> SentimentData:
        """Save sentiment data"""
        session = self.get_session()
        try:
            sentiment = SentimentData(**sentiment_data)
            session.add(sentiment)
            session.commit()
            session.refresh(sentiment)
            return sentiment
        except Exception as e:
            session.rollback()
            logger.error(f"Error saving sentiment: {e}")
            raise
        finally:
            session.close()

    def save_performance(self, perf_data: dict) -> PerformanceMetrics:
        """Save performance metrics"""
        session = self.get_session()
        try:
            perf = PerformanceMetrics(**perf_data)
            session.add(perf)
            session.commit()
            session.refresh(perf)
            return perf
        except Exception as e:
            session.rollback()
            logger.error(f"Error saving performance: {e}")
            raise
        finally:
            session.close()

    def save_prediction(self, pred_data: dict) -> MLPrediction:
        """Save ML prediction"""
        session = self.get_session()
        try:
            pred = MLPrediction(**pred_data)
            session.add(pred)
            session.commit()
            session.refresh(pred)
            return pred
        except Exception as e:
            session.rollback()
            logger.error(f"Error saving prediction: {e}")
            raise
        finally:
            session.close()

    def get_recent_trades(self, limit: int = 100) -> List[Trade]:
        """Get recent trades"""
        session = self.get_session()
        try:
            return session.query(Trade).order_by(Trade.timestamp.desc()).limit(limit).all()
        finally:
            session.close()

    def get_trades_by_symbol(self, symbol: str) -> List[Trade]:
        """Get all trades for a symbol"""
        session = self.get_session()
        try:
            return session.query(Trade).filter(Trade.symbol == symbol).order_by(Trade.timestamp).all()
        finally:
            session.close()

    def get_recent_signals(self, symbol: Optional[str] = None, limit: int = 50) -> List[Signal]:
        """Get recent signals"""
        session = self.get_session()
        try:
            query = session.query(Signal)
            if symbol:
                query = query.filter(Signal.symbol == symbol)
            return query.order_by(Signal.timestamp.desc()).limit(limit).all()
        finally:
            session.close()

    def get_sentiment_history(self, symbol: str, days: int = 7) -> List[SentimentData]:
        """Get sentiment history for a symbol"""
        session = self.get_session()
        try:
            cutoff = datetime.utcnow() - timedelta(days=days)
            return (
                session.query(SentimentData)
                .filter(SentimentData.symbol == symbol, SentimentData.timestamp >= cutoff)
                .order_by(SentimentData.timestamp)
                .all()
            )
        finally:
            session.close()

    def get_performance_history(self, days: int = 30) -> List[PerformanceMetrics]:
        """Get performance history"""
        session = self.get_session()
        try:
            from datetime import timedelta
            cutoff = datetime.utcnow() - timedelta(days=days)
            return (
                session.query(PerformanceMetrics)
                .filter(PerformanceMetrics.date >= cutoff)
                .order_by(PerformanceMetrics.date)
                .all()
            )
        finally:
            session.close()
